export const DROP_DOWN_ADD = 'DROP_DOWN_ADD';
export const DROP_DOWN_REMOVE = 'DROP_DOWN_REMOVE';
export const DROP_DOWN_DROP = 'DROP_DOWN_DROP';
export const DROP_DOWN_COLLAPSE = 'DROP_DOWN_COLLAPSE';
export const DROP_DOWN_MOUSE_OVER = 'DROP_DOWN_MOUSE_OVER';
export const DROP_DOWN_MOUSE_OUT = 'DROP_DOWN_MOUSE_OUT';
export const DROP_DOWN_SELECT = 'DROP_DOWN_SELECT';
